version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "atamanber-website"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lwz4ja2e8sbs"
s3_prefix = "atamanber-website"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
